# Site Meta
title:            plt4rm cli

domain:           cli.plt4rm.com
type:             website
logo:             /logo.png

contact:  contact@plt4rm.com
facebook: plt4rm.social
twitter: plt4rm
github: plt4rm

#Assets paths
css: /assets/css
js: /assets/js
img: /assets/img
font: /assets/font
bower:    /assets/bower_components



# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://cli.plt4rm.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ''

#
# !! You don't need to change any of the configuration flags below !!
#

highlighter: rouge
permalink: /:categories/:title/

# The release of Jekyll Now that you're using
version: v1.1.0


# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  
# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
